Jun 18 2022 15:46:47 - /code/playbooks/hello-world.yaml - Gathering Facts - gather_facts - OK - omitted

Jun 18 2022 15:46:48 - /code/playbooks/hello-world.yaml - Create a file called '/tmp/testfile.txt' with some content. - copy - OK - {"module_args": {"dest": "/tmp/testfile.txt", "src": "/root/.ansible/tmp/ansible-tmp-1655567207.6797066-55-85611996862946/source", "_original_basename": "tmpkj_iyb_p", "follow": false, "checksum": "94e66df8cd09d410c62d9e0dc59d3a884e458e05", "backup": false, "force": true, "unsafe_writes": false, "content": null, "validate": null, "directory_mode": null, "remote_src": null, "local_follow": null, "mode": null, "owner": null, "group": null, "seuser": null, "serole": null, "selevel": null, "setype": null, "attributes": null}} => {"diff": [], "dest": "/tmp/testfile.txt", "src": "/root/.ansible/tmp/ansible-tmp-1655567207.6797066-55-85611996862946/source", "md5sum": "9893532233caff98cd083a116b013c0b", "checksum": "94e66df8cd09d410c62d9e0dc59d3a884e458e05", "changed": true, "uid": 0, "gid": 0, "owner": "root", "group": "root", "mode": "0644", "state": "file", "size": 12, "_ansible_no_log": false} 

Jun 18 2022 15:46:48 - /code/playbooks/hello-world.yaml - It should always fail. - copy - FAILED - {"src": "/tmp/fileThatDoesNotExist", "dest": "/tmp/dest.txt", "module_args": {"src": "/tmp/fileThatDoesNotExist", "dest": "/tmp/dest.txt"}} => {"msg": "Could not find or access '/tmp/fileThatDoesNotExist' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option", "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/ansible/plugins/action/copy.py\", line 466, in run\n    source = self._find_needle('files', source)\n  File \"/usr/local/lib/python3.8/site-packages/ansible/plugins/action/__init__.py\", line 1364, in _find_needle\n    return self._loader.path_dwim_relative_stack(path_stack, dirname, needle)\n  File \"/usr/local/lib/python3.8/site-packages/ansible/parsing/dataloader.py\", line 341, in path_dwim_relative_stack\n    raise AnsibleFileNotFound(file_name=source, paths=[to_native(p) for p in search])\nansible.errors.AnsibleFileNotFound: Could not find or access '/tmp/fileThatDoesNotExist' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option\n", "_ansible_no_log": false, "changed": false} 

